### ISSUE TITLE
Add hover styles for list entries

### ISSUE THREAD

**Issue by FichteFoll** [aziz/tmTheme-Editor#26]
It would be nice to have some kind of visual interaction with your mouse besides the cursor. So, making the currently hovered list entry change its background color to a slightly dimmed color than the active should do the trick.

Something along the lines

``` css
.ui-sortable tr:hover:not(.selected_bgdark) {
    background: #111;
}

#gallery li:hover:not(.selected_bgdark) {
    background: #111;
}
```

works here but doesn't fit the currently selected item being a gradient too well.
